#!/bin/bash
# kinship 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    set -e -x -v -u

    echo "Value of vcfs: '${vcfs[@]}'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    vcf_files=()

    for i in ${!vcfs[@]}
    do
        vcf_file="input_${i}.vcf.gz"
        dx download "${vcfs[$i]}" -o "$vcf_file"
        vcf_files+=("$vcf_file")
        ls -l "$vcf_file"
    done

    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    apt -y update
    apt -y upgrade

    # Install prerequisites
    # wget: download BEDOPS, KING
    # bgzip2: unzip VCF files
    # libquadmath0, libgomp1: needed by KING
    # git: used to clone FastSparseGRM repo

    apt -y install wget bzip2 libquadmath0 libgomp1 git

    # Install bcftools

    mkdir bcftools
    cd bcftools
    wget https://github.com/samtools/bcftools/releases/download/1.16/bcftools-1.16.tar.bz2
    tar xvf bcftools-1.16.tar.bz2
    cd bcftools-1.16
    ./configure --prefix=/usr/local/
    make
    make install
    cd ../..
    rm -r bcftools

    # Merge VCF files into single VCF file and split multiallelics using bcdtools

    bcftools concat "${vcf_files[@]}" -o all.vcf.gz
    bcftools norm -m- all.vcf.gz -o norm.vcf.gz
    ls -ralt

    # Install plink2

    mkdir plink
    cd plink
    wget https://s3.amazonaws.com/plink2-assets/alpha3/plink2_linux_x86_64_20220814.zip
    unzip plink2_linux_x86_64_20220814.zip
    ls -ralt
    mv plink2 /usr/local/bin/
    cd ..
    rm -r plink

    # Diagnostics

    zcat norm.vcf.gz | cut -f 1-30 | grep -v "##" | head -n 5

    # Use plink2 to convert VCF to BED

    plink2 --vcf norm.vcf.gz --make-bed --out all
    ls -ralt

    # Install KING

    mkdir king
    cd king
    wget https://www.kingrelatedness.com/Linux-king.tar.gz
    tar -xzvf Linux-king.tar.gz
    rm Linux-king.tar.gz
    mv king /usr/local/bin
    cd ..
    rm -r king

    # Run KING

    king -b all.bed --ibdseg --degree 4 --cpus 4 --prefix royal

    # Install FastSparseGRM

    mkdir fsgrm
    cd fsgrm
    git clone https://github.com/rounakdey/FastSparseGRM.git
    mv FastSparseGRM/R/* .
    mv FastSparseGRM/src/* .
    rm -r FastSparseGRM
    cd ..

    # Use FastSparseGRM

    ls -ralt
    R CMD BATCH --vanilla \
        '--args --prefix.in wgs --file.seg royal.seg --num_threads 4 --degree 4 --nRandomSNPs 0 --prefix.out div' \
        fsgrm/getDivergence_wrapper.R fsgrm/getDivergence.Rout
    ls -ralt
    R CMD BATCH --vanilla \
        '--args --prefix.in wgs --file.seg royal.seg --degree 4 --file.div div.div --prefix.out unrels' \
        fsgrm/extractUnrelated_wrapper.R fsgrm/extractUnrelated.Rout
    ls -ralt
    R CMD BATCH --vanilla \
        '--args --prefix.in wgs --file.unrels unrels --prefix.out pca --no_pcs 20 --num_threads 4' \
        fsgrm/runPCA_wrapper.R fsgrm/runPCA.Rout
    ls -ralt
    R CMD BATCH --vanilla \
        '--args --prefix.in wgs --prefix.out grm --file.train unrels --file.score score --file.seg royal.seg --num_threads 4 --no_pcs 20' \
        fsgrm/calcSparseGRM_wrapper.R fsgrm/calcSparseGRM.Rout
    ls -ralt

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

    grm=$(dx upload grm --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output grm "$grm" --class=file
}
