#!/bin/bash
# maf 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    set -e -x -v -u

    echo "Value of in_bed: '$in_bed'"
    echo "Value of in_bim: '$in_bim'"
    echo "Value of in_fam: '$in_fam'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    dx download "$in_bed" -o input.bed
    dx download "$in_bim" -o input.bim
    dx download "$in_fam" -o input.fam

    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # Install plink2

    apt -y update
    apt -y upgrade

    mkdir plink
    cd plink
    wget https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20231018.zip
    unzip plink_linux_x86_64_20231018.zip
    ls -ralt
    mv plink /usr/local/bin/
    cd ..
    rm -r plink

    # Use plink to reduce number of samples

    plink --r2 inter-chr 'with-freqs' --bfile input --out output

    ls -ralt

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

    out=$(dx upload output --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output row "$out" --class=file
}
